name: Build API Docker Image

on:
  push:
    paths:
      - "app/**"
      - "models/**"
      - "Dockerfile.api"

jobs:
  build-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -f Dockerfile.api -t api-devia:latest .
